Fix freeing the same image twice
Error: `srun: error: wn101: task 0: Segmentation fault (core dumped)`.

After aliasing image_out = image_in, because the seam removal is done
in-place, we tried to free the memory for image_in and image_out,
which now tried to free the same memory twice.

Removed all free(image_out) because it now points to the same memory.